title: Anahita Karandikar
author: Anahita Karandikar
email: ak234@student.ubc.ca
description: >-
  

theme: minima

header_pages:
  - index.md
  - research/index.md
  - mentorship/index.md

minima:
  social_links:
    github: anahitakarandikar
    linkedin: https://www.linkedin.com/in/anahita-karandikar
  
