title: Anahita Karandikar
author: Anahita Karandikar
email: ak234@student.ubc.ca

description: 
  PhD Candidate in Economics  
  Fields: Behavioural Development Economics, Political Economy

theme: jekyll-theme-minimal

logo: /assets/profile.jpg

header_pages:
  - index.md
  - research/index.md
  - mentorship/index.md
