title: Your Name
author: Your Name
email: your.email@example.com
description: >-
  Personal academic website

theme: minima

header_pages:
  - index.md
  - research/index.md
  - mentorship/index.md

minima:
  social_links:
    github: yourusername
    linkedin: your-linkedin-url
