title: "Anahita Karandikar"
email: "your_email@example.com"
description: "PhD Student, Food and Resource Economics, UBC"
url: "https://anahitakarandikar.github.io"
baseurl: ""

markdown: kramdown
permalink: /:title/

collections:
  pages:
    output: true
    permalink: /:path/

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
